import { StyleSheet } from 'react-native';

export const palette = {
  bg: '#F5F2EA',
  surface: '#FFFFFF',
  surfaceSoft: '#F8FBF9',
  border: '#D3DED8',
  text: '#1C2B25',
  muted: '#5F6F67',
  primary: '#1F7A67',
  primaryStrong: '#176252',
  onPrimary: '#FFFFFF',
  dangerBg: '#FFF1F1',
  dangerText: '#9C2222',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  appFrame: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  topNav: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  appTitle: {
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0.4,
    marginBottom: 14,
    color: palette.text,
  },
  levelSwitcher: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
  },
  levelSwitcherScrollView: {
    marginTop: 16,
  },
  levelTabs: {
    flexDirection: 'row',
    gap: 8,
  },
  levelTab: {
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  levelTabActive: {
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  levelTabSingle: {
    alignSelf: 'flex-start',
  },
  levelIcon: {
    fontSize: 16,
    marginRight: 4,
  },
  levelName: {
    fontSize: 13,
    fontWeight: '600',
    color: palette.text,
  },
  levelDesc: {
    display: 'none',
  },
  levelTextActive: {
    color: palette.onPrimary,
  },
  levelArrow: {
    fontSize: 10,
    marginLeft: 6,
    color: palette.text,
  },
  levelDropdownWrap: {
    position: 'relative',
    alignSelf: 'flex-start',
  },
  levelDropdownBackdrop: {
    position: 'absolute',
    top: 0,
    left: -16,
    right: -16,
    bottom: -400,
    zIndex: 1,
  },
  levelDropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: 4,
    minWidth: 160,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: 14,
    zIndex: 2,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  levelDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  levelDropdownItemActive: {
    backgroundColor: palette.primary,
  },
  levelDropdownItemLast: {
    borderBottomWidth: 0,
  },
  mainContent: {
    padding: 16,
    paddingBottom: 96,
  },
  cardBlock: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    backgroundColor: palette.surface,
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 16,
    color: palette.text,
  },
  dataGrid: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  dataItem: {
    flex: 1,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    backgroundColor: palette.surfaceSoft,
  },
  dataLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    marginBottom: 8,
    opacity: 0.6,
  },
  dataValue: {
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 36,
  },
  dataUnit: {
    fontSize: 12,
    marginTop: 4,
  },
  weightSection: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    padding: 24,
    marginBottom: 16,
    alignItems: 'center',
    textAlign: 'center',
    backgroundColor: palette.surfaceSoft,
  },
  weightCurrent: {
    fontSize: 48,
    lineHeight: 52,
    fontWeight: '700',
  },
  weightUnit: {
    fontSize: 16,
    marginTop: 4,
  },
  weightRange: {
    marginTop: 12,
    paddingTop: 12,
    fontSize: 11,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    width: '100%',
    textAlign: 'center',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 12,
    color: palette.text,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  actionBtn: {
    width: '31%', // Approximately 1/3 width
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 8,
    alignItems: 'center',
    backgroundColor: palette.surface,
  },
  actionIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  actionLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: palette.text,
  },
  recordItem: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    backgroundColor: palette.surface,
  },
  recordHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  recordTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: palette.text,
  },
  recordTime: {
    fontSize: 11,
    color: palette.muted,
  },
  recordData: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 4,
    color: palette.text,
  },
  recordDesc: {
    fontSize: 12,
    color: palette.muted,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  navItem: {
    alignItems: 'center',
    padding: 8,
  },
  navIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  navLabel: {
    fontSize: 10,
    color: palette.muted,
  },
  navActive: {
    fontWeight: '700',
    color: palette.primaryStrong,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  modalCard: {
    flex: 1,
    backgroundColor: palette.surface,
  },
  modalHeader: {
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
  },
  closeText: {
    fontSize: 28,
    lineHeight: 28,
  },
  modalBody: {
    flex: 1,
    padding: 16,
  },
  infoBox: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceSoft,
    borderRadius: 12,
    padding: 12,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 16,
  },
  infoTitle: {
    fontWeight: '700',
    marginBottom: 4,
  },
  cameraUpload: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: palette.primary,
    backgroundColor: '#F1F8F5',
    borderRadius: 14,
    paddingVertical: 40,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 16,
  },
  cameraIcon: {
    fontSize: 48,
    marginBottom: 12,
    opacity: 0.5,
  },
  cameraText: {
    fontSize: 13,
    textAlign: 'center',
  },
  resultBox: {
    borderWidth: 1,
    borderColor: '#000000',
    padding: 10,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 10,
  },
  aiResult: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    backgroundColor: palette.surface,
  },
  aiResultTitle: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 12,
    color: palette.text,
  },
  aiTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  aiTag: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    fontSize: 11,
    color: palette.text,
  },
  aiTagHighlight: {
    backgroundColor: palette.primary,
    color: palette.onPrimary,
  },
  resultErrorBox: {
    borderWidth: 1,
    borderColor: palette.dangerText,
    backgroundColor: palette.dangerBg,
    padding: 10,
    fontSize: 12,
    color: palette.dangerText,
    lineHeight: 18,
    marginBottom: 10,
  },
  flowResult: {
    marginTop: 16,
  },
  flowItem: {
    padding: 12,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    marginBottom: 8,
    backgroundColor: palette.surface,
  },
  flowItemTotal: {
    borderWidth: 1,
    backgroundColor: palette.surfaceSoft,
  },
  flowItemTitle: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 4,
  },
  flowItemData: {
    fontSize: 11,
  },
  formGroup: {
    marginBottom: 16,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
    color: palette.text,
  },
  formInput: {
    width: '100%',
    padding: 12,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    fontSize: 14,
    backgroundColor: palette.surface,
    color: palette.text,
  },
  input: {
    width: '100%',
    padding: 12,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    fontSize: 14,
    backgroundColor: palette.surface,
    color: palette.text,
  },
  primaryBtn: {
    width: '100%',
    padding: 14,
    borderWidth: 1,
    borderColor: palette.primary,
    borderRadius: 12,
    backgroundColor: palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  primaryBtnText: {
    color: palette.onPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  primaryBtnOutline: {
    backgroundColor: palette.surface,
    borderColor: palette.border,
  },
  primaryBtnOutlineText: {
    color: palette.text,
  },
  hintText: {
    fontSize: 11,
    color: palette.muted,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    textAlign: 'center',
  },
  // the remaining bits from previous styles that were untouched
  ownershipCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    backgroundColor: palette.surface,
    padding: 10,
    marginBottom: 10,
    gap: 8,
  },
  ownershipTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
  ownershipDesc: {
    fontSize: 11,
    lineHeight: 16,
    color: palette.muted,
  },
  choiceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  choiceBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
    backgroundColor: palette.surface,
  },
  choiceBtnActive: {
    backgroundColor: palette.primary,
    borderColor: palette.primary,
  },
  choiceBtnText: {
    fontSize: 12,
    color: palette.text,
    fontWeight: '600',
  },
  choiceBtnTextActive: {
    color: palette.onPrimary,
  },
  tagChoiceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  tagBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
    backgroundColor: palette.surface,
  },
  tagBtnActive: {
    backgroundColor: palette.primaryStrong,
    borderColor: palette.primaryStrong,
  },
  tagBtnText: {
    fontSize: 12,
    color: palette.text,
    fontWeight: '600',
  },
  tagBtnTextActive: {
    color: '#ffffff',
  },
  logBox: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.surface,
    padding: 10,
    marginBottom: 10,
    gap: 4,
  },
  logTitle: {
    fontSize: 12,
    fontWeight: '700',
  },
  logLine: {
    fontSize: 11,
    lineHeight: 16,
    color: palette.muted,
  },
  loadingSpinner: {
    marginBottom: 10,
  },
});
